### ISSUE TITLE
Dialog closes immediately if Auto Switch is enabled

### ISSUE THREAD

**Issue by eddablin** [JoyHak/QuickSwitch#77]
### Checks

- [ ] I tried to fix the problem myself by reading the contents of the MsgBox and Errors.log

### Problem Description

I get the windows dialogue saying that there is a file there already do I want to overwrite as soon as I open the save dialogue?

### Log

.

**Comment by JoyHak** [comment]
Please [test the latest beta](https://github.com/JoyHak/QuickSwitch/releases/tag/1.4.1), it should be fixed...

**Comment by JoyHak** [comment]
Please [try βeta v1.4.10](https://github.com/JoyHak/QuickSwitch/releases/tag/1.4.1). Reduced disk usage _(reduced amount of read / write to config operations)._
Fixed regressions:
- "Always Auto Switch" was disabled in dialog where it was enabled
- Errors after enabling "Auto Switch" and "Close old dialog".
- "Show short path" settings options name.
- Duplicating path in dialog.

**Comment by JoyHak** [comment]
I suggest you to disable "Close old dialogs" in "Menu settings"

**Comment by CennoxX** [comment]
I have the same issue with 1.4.10, even when "Close old dialogs" is disabled.
To reproduce:

1. open folder
2. open firefox or chrome on google.com
3. press ctrl+s

The dialog is now directly closed and the file saved, it's not possible to change paths.
Without QuickSwitch running I can choose my path, save the site.

<details>
<summary>QuickSwitch.ini</summary>

> [App]
> LastPath=C:\Users\user\Downloads\QuickSwitch-1.4.10-x64.exe
> MainKey=^sc10
> RestartKey=^sc1f
> AutoStartup=1
> MainFont=Tahoma
> RestartWhere=ahk_exe notepad++.exe
> MainKeyHook=1
> RestartKeyHook=0
> LastTabSettings=1
> MainIcon=      
> [Menu]
> AutoSwitch=1
> ShowAlways=0
> ShowNoSwitch=1
> ShowAfterSettings=1
> ShowAfterSelect=0
> CloseDialog=0
> ShortPath=0
> PathNumbers=0
> ShowDriveLetter=0
> ShortenEnd=0
> ShowFirstSeparator=0
> DirsCount=3
> DirNameLength=20
> PathSeparator=\
> ShortNameIndicator=..
> [Colors]
> GuiColor=      
> MenuColor=      

</details>

**Comment by JoyHak** [comment]
Confirmed. Please try [version 1.4.8 or lower](https://github.com/JoyHak/QuickSwitch/releases/tag/1.4.1). If everything is stable, I'll revert some changes.

**Comment by CennoxX** [comment]
Version 1.4.8 has the same problem.

**Comment by JoyHak** [comment]
Please try [βeta v1.4.11](https://github.com/JoyHak/QuickSwitch/releases/tag/1.4.1)
Added ability to restart all Explorer windows on system error. Improved performance by reducing disk access.
#### Improved
* Read / Write operations to reduce disk usage and improve performance.
* Values validation performance.
* Performance if the *main ini configuration* could not be accessed.
* Speed of changing path in file dialog.
* Logging about files QuickSwitch couldn't access *(including ini and TotalCmd tabbs file).*
* Logging for specific actions like deleting configuration.
* *"Menu"* tab options naming in *"Menu settings"*.
* Code readability.
#### Fixed regressions
* Turning off "close old dialog" option after opening General dialog.
* Instant file dialog closing if Auto Switch is enabled.
* Usage of wrong values entered by user in settings.

**Comment by eddablin** [comment]
Still same issue on 1.4.11 even with the close old dialogues disabled.

**Comment by eddablin** [comment]
I don't get the issue on 1.4.5

**Comment by JoyHak** [comment]
Please send a screenshot of any file dialog in which this problem appears.

**Comment by JoyHak** [comment]
To verify your assumption, I will add additional logging within an hour.

**Comment by JoyHak** [comment]
I'm sorry, I forgot to change something. Please [try v1.4.12](https://github.com/JoyHak/QuickSwitch/releases/tag/1.4.1)

**Comment by CennoxX** [comment]
> I'm sorry, I forgot to change something. Please [try v1.4.12](https://github.com/JoyHak/QuickSwitch/releases/tag/1.4.1)

1.4.12 works for me.

**Comment by eddablin** [comment]
Works for me too thank you.

**Comment by eddablin** [comment]
I am still getting issues where sometimes it tries to save the file straight away when the dialogue opens

Running 1.5.4.

**Comment by JoyHak** [comment]
Fixed. [Please download the latest version](https://github.com/JoyHak/QuickSwitch/releases/tag/1.6)

**Comment by CennoxX** [comment]
> Fixed. [Please download the latest version](https://github.com/JoyHak/QuickSwitch/releases/tag/1.6)

For me the problem still persists, for example when I press ctrl+s on Firefox sometimes it'll work as expected, but sometimes it will still directly download the site.

**Comment by JoyHak** [comment]
[Please download the latest version again](https://github.com/JoyHak/QuickSwitch/releases/tag/1.6)

**Comment by eddablin** [comment]
Just downloaded one from 35 mins ago. Will test and report back in a week. I don't always get the issue so will need to give time to see if issue remains.

**Comment by eddablin** [comment]
Same issue just happened but I can't recreate it for a gif. Will re-open this if happens again.

**Comment by JoyHak** [comment]
[Please try the latest updated release](https://github.com/JoyHak/QuickSwitch/releases)

**Comment by eddablin** [comment]
Have downloaded the new version of the 1.6 and will give a go.

**Comment by JoyHak** [comment]
In this case, a detailed report from the antivirus is required.

**Comment by JoyHak** [comment]
> ![Image](https://github.com/user-attachments/assets/22b48025-db18-4e9a-90ac-fb937ef843e7)
> 
> I get virus detected when I try to download the exe?

Fixed. New release coming soon!

![Image](https://github.com/user-attachments/assets/7d2c4943-5f7e-48ca-af8c-f50cbe6fea5b)

**Comment by eddablin** [comment]
Thank you. Yes mine says "Trojan:Win32/Sonbokli.A!cl" detected.

**Comment by JoyHak** [comment]
Fixed issues with dialog closing and antivirus warning. Please [download the latest release](https://github.com/JoyHak/QuickSwitch/releases).

**Comment by eddablin** [comment]
I'm still getting "Trojan:Win32/Sonbokli.A!cl" on 1.7

Also on 1.6 AHK version still getting issue with it trying to save straight away

![Image](https://github.com/user-attachments/assets/d93f54cd-031f-4fc4-8053-d170b2e28620)

**Comment by JoyHak** [comment]
> Also on 1.6 AHK version still getting issue with it trying to save straight away

1. Please attach a `GIF` with the file dialog opening and closing immediately. 

2. Disable `Auto switch` in the `INI` file. In this file dialog press `Ctrl+Q` (or your shortcut), open *Menu Settings > Debug > Export* and attach the exported `CSV` file here.

> You can find the `INI` and `CSV` files in the `QuickSwitch` folder.

**Comment by JoyHak** [comment]
Please try the [v1.7.1](https://github.com/JoyHak/QuickSwitch/releases/tag/1.7.1). Version 1.7.2 works slower, but the antivirus should not swear at it.

**Comment by eddablin** [comment]
I've noticed that it tries to save when I got to Listary and come back even when I'm only single clicking back...... 

![Image](https://github.com/user-attachments/assets/d43a8401-329f-47b4-bbb6-d7032e7d5dd1)

**Comment by JoyHak** [comment]
> You want me to use 1.7.1?
Yes, it's better. I'll add it to the release later.

 > I've noticed that it tries to save when I got to Listary
I'll try to fix it.

**Comment by JoyHak** [comment]
I recommend starting using Flow launcher with Everything. It is a more productive file indexing service that also supports macros and bookmarks.

**Comment by eddablin** [comment]
My whole business uses Listary. Trying Flow launcher. I'm finding the custom query shortcuts not as good as Listary filters. 

I want Listary to sort quickswtich for ARM as we are starting to switch to ARM laptops. I miss access to it I the Save As / Open dialogues. Flow Launcher or your scripts don't do that sadly. Enjoying your script in the meantime.

**Comment by JoyHak** [comment]
Custom query shortcuts can be replaced with macros of Everything: https://www.voidtools.com/forum/viewtopic.php?t=12666

There are more than a hundred commands and search results settings that can be used every day as a macro: 
```js
lastDir: Downloads => folder:nopath:sort-descending: Downloads
pic: flower => ext:jpg|png|ICO|SVG flower
```

**Comment by eddablin** [comment]
Even on 1.7.1 still getting the autosaving at random times. Will send another gif but is sometimes hard to recreate.

**Comment by JoyHak** [comment]
QuickSwitch 1.7.3+ can now change paths in active applications if the file dialog is not active. If the menu appears in the wrong application, you can always add it to the blacklist. Added the option "blacklist the Process, not the window title."

**Comment by eddablin** [comment]
Still an issue for me and it appears really randomly. Sometimes it interferes with dialogues that are nothing to do with saving or opening. It stopping me close an outlook window right now.

**Comment by JoyHak** [comment]
I can confirm that the problem is still present. I have made corrections: the delay has been increased but is only activated when the dialog is first opened. Please [download the updated archives](https://github.com/JoyHak/QuickSwitch/releases).

#### Fixed
- Missing variables errors
- Settings appeared in the center if the dialog was in the left corner of the screen.
- The QuickSwitch restart key did not work in the selected IDE/application.
- File Explorer in Win11 only displayed the first tab when the “active tab only” option was enabled.
